### ISSUE TITLE
Why is the live debugger not online anymore ? https://nodepattern.herokuapp.com/

### ISSUE THREAD

**Issue by AsWali** [rubocop/rubocop-ast#258]
I put an initial version of a live debugger at https://nodepattern.herokuapp.com/

_Originally posted by @marcandre in https://github.com/rubocop/rubocop-ast/issues/81#issuecomment-697057959_
            

I have used this site often when writing custom cops, any chance this can be deployed again ?

**Comment by marcandre** [comment]
Ah, sorry, Heroku has removed the free tier and I didn't do anything about it.
I'm contacting them now to see if we can get a FOSS free tier.

**Comment by marcandre** [comment]
In the meantime, you can install it locally: https://github.com/marcandre/np

**Comment by AsWali** [comment]
Thank you for the quick response Marc

**Comment by marcandre** [comment]
So, https://nodepattern.herokuapp.com/ is back online, with updated `rubocop-ast`, up-to-date dependencies, and improved styling thanks to @sambostock 🚀
