### ISSUE TITLE
Changelog for v1.31.2 is missing

### ISSUE THREAD

**Issue by VitaliySerov** [rubocop/rubocop-ast#287]
https://github.com/rubocop/rubocop-ast/blob/master/CHANGELOG.md#1312-2024-03-08

**Comment by bbatsov** [comment]
Yep, seems we forgot to reflect https://github.com/rubocop/rubocop-ast/pull/286 there.

**Comment by marcandre** [comment]
Right. I'll add the entry

**Comment by marcandre** [comment]
No biggie. It's true it didn't necessarily need a log entry, but it looked a bit strange without any detail.
Since this gem is very stable, there's no point in waiting for more changes, we release as soon as changes are made.
